[tool.poetry]
name = "scraper-b0e3s"
version = "0.1.0"
description = ""
authors = ["abdoul rachid fofana <rachk02@outlook.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
